# -*- coding: utf-8 -*-
"""read_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHjKcDC2-8LGLBPbmKlJFJnLyjS1-Qxe
"""



"""# Nova seção"""

import pandas as pd
musicas = pd.read_csv('./bandas.csv')
musicas.head ()

